### ISSUE TITLE
fix: importing map from clipboard not working after changing map size

### ISSUE THREAD

**Issue by novas1r1** [bluefireteam/mini_sprite#38]
**Description**
Importing the sprites library from clipboard and afterwards importing a map with a size of 16x16 it doesn't adjust the map size. Therefore I adjusted the map size and tried again. Message is telling me everything got imported, but nothing is shown. To solve this I have to reload the page, import my sprite library again, set the size of the map to 16x16 and then import my map.

Map Library String for testing:
```
barrel|16,16;20,0;10,1;5,0;1,1;10,0;1,1;4,0;12,1;5,0;10,1;6,0;1,1;1,0;6,1;1,0;1,1;6,0;1,1;8,0;1,1;5,0;3,1;6,0;3,1;4,0;12,1;5,0;1,1;1,0;6,1;1,0;1,1;6,0;1,1;2,0;4,1;2,0;1,1;6,0;2,1;6,0;2,1;6,0;10,1;6,0;1,1;1,0;6,1;1,0;1,1;5,0;2,1;8,0;2,1;4,0;12,1;1,0
platform|16,16;1,0;14,1;1,0;2,1;12,0;3,1;3,0;8,1;3,0;2,1;1,0;12,1;1,0;2,1;1,0;2,1;2,0;4,1;2,0;2,1;1,0;2,1;1,0;2,1;2,0;4,1;2,0;2,1;1,0;2,1;1,0;12,1;1,0;2,1;1,0;12,1;1,0;2,1;1,0;12,1;1,0;2,1;1,0;12,1;1,0;2,1;1,0;2,1;2,0;4,1;2,0;2,1;1,0;2,1;1,0;2,1;2,0;4,1;2,0;2,1;1,0;2,1;1,0;12,1;1,0;2,1;3,0;8,1;3,0;3,1;12,0;2,1;1,0;14,1;1,0
player|16,16;20,0;7,1;8,0;9,1;6,0;2,1;6,0;3,1;5,0;1,1;1,0;6,1;1,0;2,1;5,0;1,1;2,0;2,1;1,0;3,1;1,0;1,1;5,0;1,1;1,0;7,1;1,0;1,1;5,0;1,1;1,0;6,1;1,0;2,1;6,0;1,1;6,0;2,1;9,0;4,1;3,0;1,1;7,0;1,1;2,0;3,1;1,0;3,1;6,0;6,1;1,0;3,1;6,0;6,1;1,0;3,1;6,0;7,1;1,0;1,1;7,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;6,0
door|16,16;2,0;12,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;12,1;4,0;8,1;3,0;1,1;4,0;10,1;1,0;1,1;4,0;12,1;4,0;12,1;4,0;12,1;4,0;12,1;4,0;12,1;2,0
door_back|16,16;2,0;12,1;4,0;1,1;10,0;1,1;4,0;1,1;1,0;8,1;1,0;1,1;4,0;1,1;1,0;8,1;1,0;1,1;4,0;1,1;1,0;8,1;1,0;1,1;4,0;1,1;1,0;8,1;1,0;1,1;4,0;1,1;1,0;8,1;1,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;1,0;3,1;6,0;1,1;4,0;1,1;1,0;1,1;8,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;1,1;10,0;1,1;4,0;12,1;2,0
oxygen_bubble|16,16;21,0;6,1;8,0;2,1;6,0;2,1;5,0;1,1;10,0;1,1;3,0;1,1;2,0;2,1;8,0;1,1;2,0;1,1;1,0;2,1;9,0;1,1;1,0;1,1;2,0;1,1;11,0;2,1;2,0;1,1;11,0;2,1;14,0;2,1;14,0;2,1;14,0;1,1;1,0;1,1;12,0;1,1;2,0;1,1;12,0;1,1;3,0;1,1;10,0;1,1;5,0;2,1;6,0;2,1;8,0;6,1;5,0
spike_ball|16,16;34,0;1,1;4,0;2,1;4,0;1,1;5,0;1,1;2,0;4,1;2,0;1,1;7,0;8,1;8,0;2,1;1,0;2,1;1,0;2,1;7,0;3,1;1,0;2,1;1,0;3,1;5,0;12,1;4,0;3,1;1,0;1,1;1,0;1,1;1,0;4,1;5,0;3,1;1,0;1,1;1,0;4,1;7,0;8,1;8,0;8,1;7,0;1,1;2,0;4,1;2,0;1,1;5,0;1,1;4,0;2,1;4,0;1,1;34,0
wall_corner_top_left|16,16;17,1;15,0;1,1;1,0;15,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0
wall_corner_top_right|16,16;16,1;15,0;15,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1
wall_corner_bottom_right|16,16;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;15,1;1,0;1,1;15,0;17,1
wall_corner_bottom_left|16,16;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;15,1;15,0;16,1
wall_left|16,16;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0
wall_right|16,16;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1;13,0;1,1;1,0;1,1
wall_top|16,16;16,1;16,0;16,1;208,0
wall_bottom|16,16;208,0;16,1;16,0;16,1
spaceship_wrench|16,16;18,1;12,0;3,1;3,0;3,1;8,0;2,1;4,0;2,1;8,0;2,1;1,0;1,1;2,0;2,1;8,0;2,1;1,0;5,1;8,0;2,1;1,0;6,1;7,0;2,1;5,0;3,1;6,0;2,1;6,0;3,1;5,0;2,1;7,0;6,1;1,0;2,1;8,0;5,1;1,0;2,1;8,0;2,1;2,0;1,1;1,0;2,1;8,0;2,1;4,0;2,1;8,0;3,1;3,0;3,1;12,0;18,1
spaceship_tank|16,16;18,1;12,0;3,1;14,0;2,1;2,0;6,1;1,0;4,1;1,0;2,1;2,0;1,1;4,0;1,1;1,0;1,1;2,0;1,1;1,0;2,1;2,0;1,1;4,0;1,1;1,0;2,1;1,0;1,1;1,0;2,1;2,0;1,1;4,0;1,1;1,0;1,1;2,0;1,1;1,0;2,1;2,0;6,1;4,0;1,1;1,0;2,1;2,0;1,1;4,0;1,1;4,0;1,1;1,0;2,1;2,0;6,1;4,0;1,1;1,0;2,1;2,0;6,1;4,0;1,1;1,0;2,1;2,0;11,1;1,0;2,1;2,0;6,1;6,0;2,1;14,0;3,1;12,0;18,1
spaceship_computer|16,16;18,1;12,0;3,1;2,0;10,1;2,0;2,1;2,0;1,1;8,0;1,1;2,0;2,1;2,0;1,1;8,0;1,1;2,0;2,1;2,0;1,1;8,0;1,1;2,0;2,1;2,0;1,1;8,0;1,1;2,0;2,1;2,0;1,1;8,0;1,1;2,0;2,1;2,0;10,1;2,0;2,1;3,0;8,1;3,0;2,1;5,0;4,1;5,0;2,1;6,0;2,1;6,0;2,1;3,0;8,1;3,0;2,1;2,0;10,1;2,0;3,1;12,0;18,1
```

Map String for testing:
```
[{"x":7,"y":14,"data":{"sprite":"barrel"}},{"x":8,"y":14,"data":{"sprite":"barrel"}},{"x":6,"y":14,"data":{"sprite":"barrel"}},{"x":1,"y":9,"data":{"sprite":"barrel"}},{"x":1,"y":8,"data":{"sprite":"barrel"}},{"x":7,"y":1,"data":{"sprite":"barrel"}},{"x":8,"y":1,"data":{"sprite":"barrel"}},{"x":9,"y":1,"data":{"sprite":"barrel"}},{"x":14,"y":7,"data":{"sprite":"barrel"}},{"x":14,"y":8,"data":{"sprite":"barrel"}},{"x":14,"y":9,"data":{"sprite":"barrel"}},{"x":13,"y":7,"data":{"sprite":"barrel"}},{"x":8,"y":7,"data":{"sprite":"barrel"}},{"x":7,"y":8,"data":{"sprite":"barrel"}},{"x":9,"y":8,"data":{"sprite":"barrel"}},{"x":15,"y":0,"data":{"sprite":"wall_corner_top_right"}},{"x":14,"y":0,"data":{"sprite":"wall_top"}},{"x":13,"y":0,"data":{"sprite":"wall_top"}},{"x":12,"y":0,"data":{"sprite":"wall_top"}},{"x":11,"y":0,"data":{"sprite":"wall_top"}},{"x":10,"y":0,"data":{"sprite":"wall_top"}},{"x":9,"y":0,"data":{"sprite":"wall_top"}},{"x":8,"y":0,"data":{"sprite":"wall_top"}},{"x":7,"y":0,"data":{"sprite":"wall_top"}},{"x":6,"y":0,"data":{"sprite":"wall_top"}},{"x":5,"y":0,"data":{"sprite":"wall_top"}},{"x":3,"y":0,"data":{"sprite":"wall_top"}},{"x":1,"y":0,"data":{"sprite":"wall_top"}},{"x":4,"y":0,"data":{"sprite":"wall_top"}},{"x":2,"y":0,"data":{"sprite":"wall_top"}},{"x":0,"y":0,"data":{"sprite":"wall_corner_top_left"}},{"x":0,"y":1,"data":{"sprite":"wall_left"}},{"x":0,"y":2,"data":{"sprite":"wall_left"}},{"x":0,"y":3,"data":{"sprite":"wall_left"}},{"x":0,"y":4,"data":{"sprite":"wall_left"}},{"x":0,"y":5,"data":{"sprite":"wall_left"}},{"x":0,"y":6,"data":{"sprite":"wall_left"}},{"x":0,"y":7,"data":{"sprite":"wall_left"}},{"x":0,"y":8,"data":{"sprite":"wall_left"}},{"x":0,"y":9,"data":{"sprite":"wall_left"}},{"x":0,"y":10,"data":{"sprite":"wall_left"}},{"x":0,"y":11,"data":{"sprite":"wall_left"}},{"x":0,"y":13,"data":{"sprite":"wall_left"}},{"x":0,"y":12,"data":{"sprite":"wall_left"}},{"x":0,"y":14,"data":{"sprite":"wall_left"}},{"x":2,"y":15,"data":{"sprite":"wall_bottom"}},{"x":0,"y":15,"data":{"sprite":"wall_corner_bottom_left"}},{"x":1,"y":15,"data":{"sprite":"wall_bottom"}},{"x":3,"y":15,"data":{"sprite":"wall_bottom"}},{"x":4,"y":15,"data":{"sprite":"wall_bottom"}},{"x":5,"y":15,"data":{"sprite":"wall_bottom"}},{"x":6,"y":15,"data":{"sprite":"wall_bottom"}},{"x":7,"y":15,"data":{"sprite":"wall_bottom"}},{"x":8,"y":15,"data":{"sprite":"wall_bottom"}},{"x":11,"y":15,"data":{"sprite":"wall_bottom"}},{"x":10,"y":15,"data":{"sprite":"wall_bottom"}},{"x":9,"y":15,"data":{"sprite":"wall_bottom"}},{"x":12,"y":15,"data":{"sprite":"wall_bottom"}},{"x":13,"y":15,"data":{"sprite":"wall_bottom"}},{"x":14,"y":15,"data":{"sprite":"wall_bottom"}},{"x":15,"y":15,"data":{"sprite":"wall_corner_bottom_right"}},{"x":15,"y":14,"data":{"sprite":"wall_right"}},{"x":15,"y":13,"data":{"sprite":"wall_right"}},{"x":15,"y":12,"data":{"sprite":"wall_right"}},{"x":15,"y":11,"data":{"sprite":"wall_right"}},{"x":15,"y":10,"data":{"sprite":"wall_right"}},{"x":15,"y":9,"data":{"sprite":"wall_right"}},{"x":15,"y":8,"data":{"sprite":"wall_right"}},{"x":15,"y":7,"data":{"sprite":"wall_right"}},{"x":15,"y":6,"data":{"sprite":"wall_right"}},{"x":15,"y":5,"data":{"sprite":"wall_right"}},{"x":15,"y":4,"data":{"sprite":"wall_right"}},{"x":15,"y":2,"data":{"sprite":"wall_right"}},{"x":15,"y":1,"data":{"sprite":"wall_right"}},{"x":15,"y":3,"data":{"sprite":"wall_right"}},{"x":2,"y":13,"data":{"sprite":"platform"}},{"x":3,"y":13,"data":{"sprite":"platform"}},{"x":4,"y":13,"data":{"sprite":"platform"}},{"x":5,"y":13,"data":{"sprite":"platform"}},{"x":6,"y":12,"data":{"sprite":"platform"}},{"x":7,"y":10,"data":{"sprite":"platform"}},{"x":8,"y":11,"data":{"sprite":"platform"}},{"x":9,"y":11,"data":{"sprite":"platform"}},{"x":9,"y":13,"data":{"sprite":"platform"}},{"x":10,"y":13,"data":{"sprite":"platform"}},{"x":12,"y":13,"data":{"sprite":"platform"}},{"x":13,"y":14,"data":{"sprite":"platform"}},{"x":11,"y":11,"data":{"sprite":"platform"}},{"x":10,"y":11,"data":{"sprite":"platform"}},{"x":6,"y":10,"data":{"sprite":"platform"}},{"x":5,"y":10,"data":{"sprite":"platform"}},{"x":3,"y":3,"data":{"sprite":"oxygen_bubble"}},{"x":3,"y":9,"data":{"sprite":"oxygen_bubble"}},{"x":14,"y":11,"data":{"sprite":"oxygen_bubble"}},{"x":10,"y":3,"data":{"sprite":"oxygen_bubble"}},{"x":9,"y":14,"data":{"sprite":"oxygen_bubble"}},{"x":7,"y":5,"data":{"sprite":"spike_ball"}},{"x":12,"y":14,"data":{"sprite":"platform"}},{"x":13,"y":13,"data":{"sprite":"door"}},{"x":2,"y":12,"data":{"sprite":"spaceship_wrench"}},{"x":1,"y":2,"data":{"sprite":"player"}},{"x":1,"y":3,"data":{"sprite":"platform"}},{"x":2,"y":3,"data":{"sprite":"platform"}}]
```

**Steps To Reproduce**

1. Sprite tab: Import sprites library from clipboard
2. Map tab: Import map from clipboard
3. Change map size to 16x16
4. Reimport map from clipboard
5. Success message is shown, but nothing is imported

**Expected Behavior**
Two possibilities:
1. Adjust the map to the size which was used to create the map
2. Clearing the map, adjusting the size manually and then be able to paste the map in without refreshing and reimporting everything.

**Screenshots**
Imported map from clipboard:
![image](https://user-images.githubusercontent.com/2575205/186255053-c3f20672-7665-4c9d-80cf-d115768d8ead.png)

Adjusting the size:
![image](https://user-images.githubusercontent.com/2575205/186255086-7bd0a116-91bd-43a2-9a9c-7333a6fb9545.png)

Reimporting map from clipboard:
![image](https://user-images.githubusercontent.com/2575205/186255129-a60a23c3-5901-485b-9d4a-f7dfd81dd7bb.png)

**Comment by novas1r1** [comment]
Ha, I just found out something. So when importing works with the workaround mentioned above and then exporting the String again I'm getting something starting with this:

```
{"width":16,"height":16,"objects":[{"x":7,"y":14,"data":{"sprite":"barrel"}},{"x":8,"y":14,"data":{"sprite":"barrel"}},{"x":6,"y":14,"data":{"sprite":"barrel"}},{"x":1,"y":9,"data":
...
```
I guess that's what width and height are for but when I'm replacing my current map string from the bug example I'm getting this error when running the game and don't see any map:

```
Error: Expected a value of type 'List<dynamic>', but got one of type '_JsonMap'
    at Object.throw_ [as throw] (http://localhost:59500/dart_sdk.js:5080:11)
    at Object.castError (http://localhost:59500/dart_sdk.js:5039:15)
    at Object.cast [as as] (http://localhost:59500/dart_sdk.js:5356:17)
    at List.as_C [as as] (http://localhost:59500/dart_sdk.js:4985:19)
at MiniMap.fromDataString (http://localhost:59500/packages/mini_sprite/src/mini_map.dart.lib.js:45:31)
at game$.GameEntity.new.onLoad$ (http://localhost:59500/packages/flamejam/start/view/start_page.dart.lib.js:2153:36)
    at onLoad$.next (<anonymous>)
    at http://localhost:59500/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:59500/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:59500/dart_sdk.js:35438:29)
    at handleValueCallback (http://localhost:59500/dart_sdk.js:35999:49)
    at _Future._propagateToListeners (http://localhost:59500/dart_sdk.js:36037:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59500/dart_sdk.js:35753:27)
    at Object._microtaskLoop (http://localhost:59500/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:59500/dart_sdk.js:40784:13)
    at http://localhost:59500/dart_sdk.js:36261:9
```

**Comment by novas1r1** [comment]
Okay,  great, just found out you fixed it already ^^. Was too slow updating...

**Comment by erickzanardo** [comment]
Hey sorry for the confusion, the `width` and `height` getters were introduced on mini sprite `0.0.2`, so that could happen if you had a raw string generated with the old version.
